.Dd Apr 8, 2017
.Os
.Dt HDNEWS-GIT 1
.
.Sh NAME
.Nm hdnews-git
.Nd Executes
.Xr git 1 in the hdnews git work tree.
.
.Sh SYNOPSIS
Same as
.Xr git 1 .
.
.Sh EXAMPLES
hdnews-git remote add origin <remote>
.br
hdnews-git push -u origin master
.sp
.Sh DIAGNOSTICS
Same as
.Xr git 1 .
.Sh SEE ALSO
.Bl
.It
.Xr hdnews-init 1 .
.Xr git 1 .
.El
.Sh LICENSE
BSD-3
.Lk https://github.com/yaccz/hdnews/blob/master/LICENSE
.Sh AUTHORS
.An Jan Matějka Aq Mt yac@blesmrt.net
.Lk https://github.com/yaccz/hdnews/
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/yaccz/hdnews/issues
