.Dd Mar 20, 2017
.Os
.Dt HDNEWS-ADD 1
.
.Sh NAME
.Nm hdnews-add
.Nd Add a news record into hdnews git database
.
.Sh DESCRIPTION
hdnews-add creates a new directory named by integer successor of
/news/.last_id content in git repository initialized by
.Xr hdnews-init 1 .
.sp
This directory makes up a root of news record. Inside the news record
there is a file source containing the contents of X primary selection at
the time of hdnews-add invocation.
.sp
Then vim editor is opened to possibly correct source and enter
description.
.sp
When the vim editor is closed, the news record is committed.
.sp
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Bl
.It
.Xr hdnews-init 1 . git-commit 1 .
.El
.Sh LICENSE
BSD-3
.Lk https://github.com/yaccz/hdnews/blob/master/LICENSE
.Sh AUTHORS
.An Jan Matějka Aq Mt yac@blesmrt.net
.Lk https://github.com/yaccz/hdnews/
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/yaccz/hdnews/issues
